Feature
Mastermind-sap/joker pull request #3
Opened 2020-11-25 18:23 UTC by JDeepD

2020-11-25 18:24 UTC, JDeepD commented
Added reddit memes fetching
Modified README

2020-11-25 18:25 UTC, JDeepD commented
Donot merge yet

2020-11-25 18:26 UTC, JDeepD commented
Wait for sometime

2020-11-25 18:29 UTC, Mastermind-sap commented
Outdated @JDeepD

2020-11-25 18:45 UTC, Mastermind-sap commented
Make a new pr after forking or fetching the changes from the master branch of my repo. And plz check the command name shouldnot conflict with other commands. Also what is pip lock and pip, i guess only the main files would be better to keep

2020-11-25 18:45 UTC, JDeepD commented
abbey chutiye

2020-11-25 18:46 UTC, JDeepD commented
mai rebase kr rha tha toh

2020-11-25 18:53 UTC, Mastermind-sap commented
woh kya hota hai? :laughing:

2020-11-25 18:59 UTC, JDeepD commented
ruk. dont merge

2020-11-25 19:03 UTC, Mastermind-sap commented
> ruk. dont merge

nhi krunga...lekin rebassing kya hai

2020-11-25 19:15 UTC, JDeepD commented
merge kr skta hai ab

2020-11-25 19:19 UTC, JDeepD commented
> Make a new pr after forking or fetching the changes from the master branch of my repo. And plz check the command name shouldnot conflict with other commands. Also what is pip lock and pip, i guess only the main files would be better to keep

It will not conflct with the working of the bot. If you dont want them, you can delete them after merging. I need them because I work in a venv and without those files, the venv wont be created.
Also make sure you do a `pip install -r requirements.txt` before running it from the local machine.
If running from heroku, then its not required

2020-11-25 19:42 UTC, Mastermind-sap commented
Aree i cannot merge it.....i dont know why! and what merge should i do

2020-11-26 03:05 UTC, JDeepD commented
Merge it now. Why did you make another commit 7 hrs ago before merging this PR?

2020-11-26 04:56 UTC, Mastermind-sap commented
> Merge it now. Why did you make another commit 7 hrs ago before merging this PR?

I did not see your PR.

2020-11-26 05:16 UTC, Mastermind-sap requested changes
Please look into the reviews and bring the necessary changes. After that I will accept it. 
Thank you for your contribution.

2020-11-26 05:16 UTC, Mastermind-sap commented on joker.py
> +
This part is repeated.

2020-11-26 05:16 UTC, Mastermind-sap commented on joker.py
> +
Bot command conflicting with already present commands

2020-11-26 05:16 UTC, Mastermind-sap commented on help.md
The format of help is not correct. It should be:
```
- < command name >

functionality of the command or what it does
```

2020-11-26 05:16 UTC, Mastermind-sap commented on apis/redditapi.py
> +reddit = praw.Reddit(
Is this api key yours or is it a public key?

2020-11-26 05:16 UTC, Mastermind-sap commented on apis/redditapi.py
> +
Why the name of subreddit is linuxmemes.....change it to something more general plz

2020-11-26 05:16 UTC, Mastermind-sap commented on README.md
> +| `!joker search`      | search for query and return n number of results (max n=5) | `-`                                 | `no. of results to be fetched`          |
Some recent commands are missing!

2020-11-26 05:16 UTC, Mastermind-sap commented on README.md
> +| Command              | Task                                                      | Aliases                             | Parameters                              |
Good that you are giving in tabulated form but why you removed the first two lines. I guess it would be better if it remains in the readme.md

2020-11-26 05:26 UTC, closed without merging

2020-11-26 05:28 UTC, JDeepD commented on README.md
> +| Command              | Task                                                      | Aliases                             | Parameters                              |
*Because that is a command and it was added in the table*

2020-11-26 05:29 UTC, JDeepD commented on README.md
> +| `!joker search`      | search for query and return n number of results (max n=5) | `-`                                 | `no. of results to be fetched`          |
What?

2020-11-26 05:30 UTC, JDeepD commented on apis/redditapi.py
> +
Thats literally renaming a word and could have been changed after merge

2020-11-26 05:31 UTC, JDeepD commented on apis/redditapi.py
> +reddit = praw.Reddit(
Its kind of in between

2020-11-26 05:32 UTC, JDeepD commented on help.md
What is the need for a separate `help.md` when literally every thing there is present in `README.md` ?